services:

  eureka-server:
    build:
      context: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    restart: always

  gestionclinica:
    build:
      context: ./gestionclinica
    container_name: gestionclinica
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: aws
    depends_on:
      - eureka-server
    restart: always

  gestionsoporte:
    build:
      context: ./gestionsoporte
    container_name: gestionsoporte
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: aws
    depends_on:
      - eureka-server
    restart: always

  bff:
    build:
      context: ./bff-rednote
    container_name: bff
    ports:
      - "8090:8090"
    environment:
      SPRING_PROFILES_ACTIVE: aws
    depends_on:
      - eureka-server
      - gestionclinica
      - gestionsoporte
    restart: always

  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    ports:
      - "8085:8085"
    environment:
      BFF_URL: http://bff:8090
      EUREKA_URL: http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
      - bff
    restart: always

  frontend:
    build:
      context: ./rednorte-frontend
      args:
        VITE_API_BFF_URL: http://32.197.111.18:8085/api/bff
    container_name: frontend
    ports:
      - "5173:80"
    depends_on:
      - api-gateway
    restart: always