

services:

  gestionclinica:
    build:
      context: ./gestionclinica
    container_name: gestionclinica
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: aws

  gestionsoporte:
    build:
      context: ./gestionsoporte
    container_name: gestionsoporte
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: aws

  bff:
    build:
      context: ./bff-rednote
    container_name: bff
    ports:
      - "8090:8090"
    environment:
      SPRING_PROFILES_ACTIVE: aws

  frontend:
    build:
      context: ./rednorte-frontend
    container_name: frontend
    ports:
      - "5173:80"