server.port=8090

gestion.clinica.url=http://gestionclinica:8081
gestion.soporte.url=http://gestionsoporte:8082

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true