name: RedNorte CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  build-backends:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - gestionclinica
          - gestionsoporte
          - bff-rednote

    steps:

      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Compilar backend
        working-directory: ./${{ matrix.service }}
        run: mvn clean package -DskipTests

  build-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Instalar dependencias
        working-directory: ./rednorte-frontend
        run: npm install

      - name: Compilar frontend
        working-directory: ./rednorte-frontend
        run: npm run build